# Generated by Django 5.0.7 on 2024-08-01 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MandatoryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(unique=True)),
                ('channel_id', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('YIGITLAR', 'Yigitlar'), ('QIZLAR', 'Qizlar'), ('JUFLIKLAR', 'Jufliklar'), ('KANALLAR_UCHUN', 'Kanallar uchun'), ('MULTIK_RASM', 'Multik Rasm'), ('JUMA_TABRIGI', 'Juma Tabrigi'), ('TURLICHA_LOGO', 'Turlicha logo'), ('PABG_UCHUN', 'Pabg uchun'), ('MUSLIM_VA_MUSLIMALAR', 'Muslim Va Muslimalar uchun'), ('KOZGA_ISM', "Ko'zga ism"), ('TUGILGAN_KUN', "Tug'ilgan kun"), ('DOSTLARGA', "Do'stlarga"), ('DUGONALARGA', 'Dugonalarga'), ('BOTLAR_UCHUN', 'Botlar uchun'), ('FUTBOLKA_UCHUN', 'Futbolka uchun')], max_length=50)),
                ('roleimage_mandatory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_mandatory', to='bot.mandatoryuser')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='roles_images/')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bot.rolesimage')),
            ],
        ),
        migrations.AddField(
            model_name='mandatoryuser',
            name='chat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandatory', to='bot.user'),
        ),
    ]
