# Generated by Django 5.0 on 2024-08-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namerole',
            name='name',
            field=models.CharField(choices=[('Yigitlar', 'Yigitlar'), ('Qizlar', 'Qizlar'), ('Juftliklar', 'Juftliklar')], max_length=500),
        ),
    ]
