# Generated by Django 5.0 on 2024-08-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_ordervideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordervideo',
            name='channel_id',
            field=models.CharField(default='bot', max_length=20),
            preserve_default=False,
        ),
    ]
